import type { MedicalRecord, Medication, SymptomLog, Note, ProviderConnection, Observation } from '@/types'

export const mockUser = {
  id: 'user-1',
  email: 'sarah.johnson@example.com',
  name: 'Sarah Johnson',
  avatar: null,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
}

export const mockProfile = {
  id: 'profile-1',
  userId: 'user-1',
  dateOfBirth: new Date('1988-03-15'),
  bloodType: 'A+',
  height: 165,
  weight: 62,
  allergies: ['Penicillin', 'Sulfa drugs', 'Shellfish'],
  emergencyContact: {
    name: 'Michael Johnson',
    relationship: 'Spouse',
    phone: '+1 (555) 123-4567',
    email: 'michael.j@example.com',
  },
  isAnonymized: false,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
}

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: 'record-1',
    userId: 'user-1',
    title: 'Annual Blood Panel',
    type: 'lab',
    date: new Date('2024-02-15'),
    provider: 'City Medical Center',
    sourceType: 'FHIR',
    isHidden: false,
    isEdited: false,
    originalData: null,
    editedData: null,
    notes: 'Routine annual bloodwork. All markers within normal range.',
    attachmentUrl: null,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'record-2',
    userId: 'user-1',
    title: 'Primary Care Visit',
    type: 'visit',
    date: new Date('2024-02-01'),
    provider: 'Dr. Emily Chen',
    sourceType: 'MANUAL',
    isHidden: false,
    isEdited: false,
    originalData: null,
    editedData: null,
    notes: 'Annual wellness checkup. Blood pressure 118/76. Discussed lifestyle changes.',
    attachmentUrl: null,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'record-3',
    userId: 'user-1',
    title: 'Chest X-Ray',
    type: 'imaging',
    date: new Date('2024-01-20'),
    provider: 'Radiology Associates',
    sourceType: 'OCR',
    isHidden: false,
    isEdited: true,
    originalData: null,
    editedData: null,
    notes: 'Clear lungs. No abnormalities detected.',
    attachmentUrl: null,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'record-4',
    userId: 'user-1',
    title: 'Lipid Panel Results',
    type: 'lab',
    date: new Date('2024-01-10'),
    provider: 'LabCorp',
    sourceType: 'FHIR',
    isHidden: false,
    isEdited: false,
    originalData: null,
    editedData: null,
    notes: 'LDL slightly elevated at 132 mg/dL. Follow up in 3 months.',
    attachmentUrl: null,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'record-5',
    userId: 'user-1',
    title: 'Dermatology Consultation',
    type: 'visit',
    date: new Date('2023-12-18'),
    provider: 'Dr. Mark Williams',
    sourceType: 'MANUAL',
    isHidden: false,
    isEdited: false,
    originalData: null,
    editedData: null,
    notes: 'Reviewed skin concerns. Prescribed topical retinol cream.',
    attachmentUrl: null,
    createdAt: new Date('2023-12-18'),
    updatedAt: new Date('2023-12-18'),
  },
]

export const mockMedications: Medication[] = [
  {
    id: 'med-1',
    userId: 'user-1',
    name: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Once daily',
    startDate: new Date('2023-06-01'),
    endDate: null,
    isActive: true,
    prescribedBy: 'Dr. Emily Chen',
    notes: 'Take in the morning with water.',
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2023-06-01'),
  },
  {
    id: 'med-2',
    userId: 'user-1',
    name: 'Atorvastatin',
    dosage: '20mg',
    frequency: 'Once daily at bedtime',
    startDate: new Date('2024-01-15'),
    endDate: null,
    isActive: true,
    prescribedBy: 'Dr. Emily Chen',
    notes: 'Monitor for muscle pain.',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'med-3',
    userId: 'user-1',
    name: 'Vitamin D3',
    dosage: '2000 IU',
    frequency: 'Once daily',
    startDate: new Date('2023-09-01'),
    endDate: null,
    isActive: true,
    prescribedBy: null,
    notes: 'OTC supplement for deficiency.',
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2023-09-01'),
  },
  {
    id: 'med-4',
    userId: 'user-1',
    name: 'Amoxicillin',
    dosage: '500mg',
    frequency: 'Three times daily',
    startDate: new Date('2023-11-01'),
    endDate: new Date('2023-11-10'),
    isActive: false,
    prescribedBy: 'Dr. Sarah Park',
    notes: 'Completed course for sinus infection.',
    createdAt: new Date('2023-11-01'),
    updatedAt: new Date('2023-11-10'),
  },
]

export const mockSymptomLogs: SymptomLog[] = [
  {
    id: 'sym-1',
    userId: 'user-1',
    symptomName: 'Headache',
    severity: 5,
    notes: 'Started after lunch, likely tension headache.',
    date: new Date('2024-02-20'),
    createdAt: new Date('2024-02-20'),
  },
  {
    id: 'sym-2',
    userId: 'user-1',
    symptomName: 'Fatigue',
    severity: 4,
    notes: 'Feeling tired despite 8 hours of sleep.',
    date: new Date('2024-02-19'),
    createdAt: new Date('2024-02-19'),
  },
  {
    id: 'sym-3',
    userId: 'user-1',
    symptomName: 'Back Pain',
    severity: 3,
    notes: 'Lower back after long desk session.',
    date: new Date('2024-02-18'),
    createdAt: new Date('2024-02-18'),
  },
  {
    id: 'sym-4',
    userId: 'user-1',
    symptomName: 'Headache',
    severity: 7,
    notes: 'Severe migraine with light sensitivity.',
    date: new Date('2024-02-15'),
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'sym-5',
    userId: 'user-1',
    symptomName: 'Nausea',
    severity: 4,
    notes: 'Brief nausea in the morning.',
    date: new Date('2024-02-12'),
    createdAt: new Date('2024-02-12'),
  },
  {
    id: 'sym-6',
    userId: 'user-1',
    symptomName: 'Fatigue',
    severity: 6,
    notes: 'Exhausted after travel.',
    date: new Date('2024-02-10'),
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'sym-7',
    userId: 'user-1',
    symptomName: 'Headache',
    severity: 3,
    notes: 'Mild headache, resolved with water.',
    date: new Date('2024-02-08'),
    createdAt: new Date('2024-02-08'),
  },
]

export const mockNotes: Note[] = [
  {
    id: 'note-1',
    userId: 'user-1',
    recordId: 'record-2',
    title: 'Dr. Chen Visit Notes',
    content: 'Discussed reducing sodium intake. She recommended the DASH diet. Follow-up in 6 months. BP goal is under 120/80.',
    appointmentDate: new Date('2024-02-01'),
    tags: ['cardiology', 'diet', 'blood-pressure'],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'note-2',
    userId: 'user-1',
    recordId: null,
    title: 'Pharmacy Questions',
    content: 'Ask about generic options for Atorvastatin. Check insurance coverage for vitamin supplements.',
    appointmentDate: null,
    tags: ['pharmacy', 'insurance'],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'note-3',
    userId: 'user-1',
    recordId: 'record-4',
    title: 'Lipid Panel Follow-up Reminders',
    content: 'LDL at 132 - target is under 100. Increase fiber intake, add omega-3 supplement. Retest in March.',
    appointmentDate: new Date('2024-04-10'),
    tags: ['cholesterol', 'diet', 'labs'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
]

export const mockProviders: ProviderConnection[] = [
  {
    id: 'prov-1',
    userId: 'user-1',
    providerName: 'City Medical Center',
    providerType: 'Hospital',
    status: 'connected',
    lastSynced: new Date('2024-02-15'),
    authToken: null,
    endpoint: 'https://fhir.citymedical.example.com',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'prov-2',
    userId: 'user-1',
    providerName: 'LabCorp',
    providerType: 'Laboratory',
    status: 'connected',
    lastSynced: new Date('2024-01-10'),
    authToken: null,
    endpoint: 'https://api.labcorp.example.com',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'prov-3',
    userId: 'user-1',
    providerName: 'CVS Health',
    providerType: 'Pharmacy',
    status: 'pending',
    lastSynced: null,
    authToken: null,
    endpoint: null,
    createdAt: new Date('2024-02-18'),
    updatedAt: new Date('2024-02-18'),
  },
]

export const mockObservations: Observation[] = [
  {
    id: 'obs-1',
    recordId: 'record-1',
    userId: 'user-1',
    type: 'Hemoglobin',
    value: '13.8',
    unit: 'g/dL',
    date: new Date('2024-02-15'),
    referenceRange: '12.0-17.5',
    isAbnormal: false,
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'obs-2',
    recordId: 'record-1',
    userId: 'user-1',
    type: 'WBC',
    value: '7.2',
    unit: 'K/uL',
    date: new Date('2024-02-15'),
    referenceRange: '4.5-11.0',
    isAbnormal: false,
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'obs-3',
    recordId: 'record-4',
    userId: 'user-1',
    type: 'LDL Cholesterol',
    value: '132',
    unit: 'mg/dL',
    date: new Date('2024-01-10'),
    referenceRange: '<100',
    isAbnormal: true,
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'obs-4',
    recordId: 'record-4',
    userId: 'user-1',
    type: 'HDL Cholesterol',
    value: '58',
    unit: 'mg/dL',
    date: new Date('2024-01-10'),
    referenceRange: '>40',
    isAbnormal: false,
    createdAt: new Date('2024-01-10'),
  },
]

export const symptomTrendData = [
  { date: 'Feb 8', headache: 3, fatigue: 2, backPain: 1 },
  { date: 'Feb 10', headache: 2, fatigue: 6, backPain: 2 },
  { date: 'Feb 12', headache: 1, fatigue: 4, backPain: 2 },
  { date: 'Feb 15', headache: 7, fatigue: 5, backPain: 3 },
  { date: 'Feb 18', headache: 2, fatigue: 3, backPain: 3 },
  { date: 'Feb 19', headache: 1, fatigue: 4, backPain: 2 },
  { date: 'Feb 20', headache: 5, fatigue: 3, backPain: 2 },
]

export const medicationAdherence = [
  { name: 'Lisinopril', taken: 27, total: 29, percentage: 93 },
  { name: 'Atorvastatin', taken: 25, total: 29, percentage: 86 },
  { name: 'Vitamin D3', taken: 22, total: 29, percentage: 76 },
]
